version: "3"

services:
  client:
    build: .
    container_name: client
    ports:
      - "8080:8080"
    environment:
      - VITE_SOCKET_URL=https://server:8000
    networks:
      pixie:

networks:
  pixie:
